export global AppState {
    // Properties.
    in property <bool> valid_cusip;
    out property <string> cusip;
    in property <int> takedown;
    in property <string> lookback;
    // Can be: 2yr, 3yr, 5yr, 7yr, 10yr, 20yr, 30yr.
    in property <string> auction-type;

    
    // Callbacks.
    callback takedown-changed(int);
    pure callback set-cusip(string); 
    pure callback validate_cusip(string) -> bool;
    pure callback render_plot(length, length, int) -> image;

    // Functions.
    public function set-the-cusip(cu: string) {
        debug("Im setting the cusip: " + cu);
        cusip = cu;
        AppState.set-cusip(cu);
    }
}