// Provides data that can be reused

export global HeaderData {
    out property <[TableColumn]> header: [
        { title: "No." },
        { title: "Security Term" },
        { title: "CUSIP" },
        { title: "Reopen?" },
        { title: "Type" },
        { title: "BTC" },
        { title: "Dealers %" },
        { title: "Directs %" },
        { title: "Indirects %" },
        { title: "Yield" },
        { title: "Interest" },
    ];
}
