import { VerticalBox, Button, HorizontalBox, LineEdit, StandardTableView, GroupBox, TabWidget, ListView, StandardButton } from "std-widgets.slint";
import { CusipInput } from "cusipinput.slint";
import { SecurityDisplay, SlMap } from "securitydisplay.slint";
import { AppState } from "appstate.slint";
import { SecuritiesTableAdapter } from "tableadapters.slint";

export { AppState, SecuritiesTableAdapter, SlMap }

export component AppWindow inherits Window {
    callback close;
    title: "Iron - The auction result viewer";
    preferred_width: 640px;
    preferred_height: 480px;
    VerticalLayout {
        padding: 20px;
        spacing: 20px;
        HorizontalLayout {
            spacing: 10px;
            CusipInput { }
        }

        HorizontalLayout {
            Rectangle {
                height: 2px;
                background: grey;
            }
        }

        HorizontalBox {
            padding: 0px;
            spacing: 0px;
            TabWidget {
                Tab {
                    title: "Detail Data";
                    VerticalBox {
                        details-display := StandardTableView {
                            vertical-stretch: 1;
                            // columns: [
                            //     { title: "Header 1" },
                            //     { title: "Header 2" },
                            // ];
                        }
                    }
                    // security-display := SecurityDisplay { }
                }

                Tab {
                    title: "Securities";
                    VerticalBox {
                        securities := StandardTableView {
                            vertical-stretch: 1;
                            columns: [];
                            rows: SecuritiesTableAdapter.row_data ;
                        }
                    }
                }

                Tab {
                    title: "Auction Quality";
                    VerticalBox {
                        quality := StandardTableView {
                            vertical-stretch: 1;
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            Rectangle {
                height: 2px;
                background: gray;
            }
        }

        HorizontalLayout {
            Rectangle { }

            Button {
                text: "Close";
                clicked => {
                    close();
                }
            }
        }
    }
}
